# Press [<prefix> r (Ctrl + s - r)] for reload 
# Press 

# Use mouse in tmux
set -g mouse on

# Display specific color
set  -g default-terminal "screen-256color"

# Move status bar to top 
set-option -g status-position top

# Setting-terminal prefix control pane
unbind C-b 
set -g prefix C-s 
bind-key C-s send-prefix

# Setting split pane vertical and horizonal
unbind  % 
bind '\' split-window -h -c '#{pane_current_path}' # horizonal

unbind '"'
bind - split-window -v -c '#{pane_current_path}' # vertical

# Set key for reload Setting
unbind r
bind r source-file ~/.tmux.conf 

# Copy to clipboard 
# bind -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel "xclip -se c -i"

# Setting key vim-mode for interact in tmux
setw -g mode-keys vi 
bind -r v copy-mode 
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X stop-selection 

# Resize-pane
bind -r C-Down resize-pane -D 5 
bind -r C-Up resize-pane -U 5 
bind -r C-Left resize-pane -L 5 
bind -r C-Right resize-pane -R 5 

bind -r z resize-pane -Z 

# Move pane
bind -r j select-pane -D
bind -r k select-pane -U
bind -r h select-pane -L
bind -r l select-pane -R

unbind Up
unbind Down 
unbind Left 
unbind Right 

# unbind C-Up
# unbind C-Down 
# unbind C-Left 
# unbind C-Right 
# # Start index pane from 1 -> s
set-option -g base-index 1

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator' # using vim-tmux-navigator
set -g @plugin 'catppuccin/tmux#v2.3.1' # themes awesome 
set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-sensible' 

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
# For TPM, instead use `run ~/.tmux/plugins/tmux/catppuccin.tmux`

# -------------------------------------------------- 
# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
run ~/.config/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux
# ------------------------------------------------
# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'github_username/plugin_name#branch'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
