# Insert your preferred key mappings here.
# using q for hint search feature 
unmap f
map q LinkHints.activateMode

# using shift T for navigate search engineer 
unmap t
map T Vomnibar.activateTabSelection
