# Use mouse in tmux
set -g mouse on

# Display specific color
set  -g default-terminal "screen-256color"

# Using vim-tmux-navigator
set -g @plugin 'christoomey/vim-tmux-navigator'

# Setting-terminal prefix control pane
unbind C-b 
set -g prefix C-a 
bind-key C-a send-prefix

# Setting split pane vertical and horizonal
unbind  % 
bind '\' split-window -h -c '#{pane_current_path}' # horizonal

unbind '"'
bind - split-window -v -c '#{pane_current_path}' # vertical

# Set key for reload Setting
unbind r
bind r source-file ~/.tmux.conf 

# Copy to clipboard 
# bind -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel "xclip -se c -i"

# Setting key vim-mode for interact in tmux
setw -g mode-keys vi 
bind -r v copy-mode 
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# Resize-pane
bind -r C-j resize-pane -D 5 
bind -r C-k resize-pane -U 5 
bind -r C-h resize-pane -L 5 
bind -r C-l resize-pane -R 5 

bind -r z resize-pane -Z 

# Move pane
bind -r j select-pane -D
bind -r k select-pane -U
bind -r h select-pane -L
bind -r l select-pane -R

unbind Up
unbind Down 
unbind Left 
unbind Right 

unbind C-Up
unbind C-Down 
unbind C-Left 
unbind C-Right 
# Start index pane from 1 -> s
set-option -g base-index 1
